spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-59ys1ptm.sql.tencentcdb.com:28262/wu_ye?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf-8
    username: root
    password: "!yanruisong123"
  main:
    banner-mode: off
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
ding:
  clientId: dingjbyp6ttfg0ujtzrd
  clientSecret: cJwPwL5djhn5nl-xG09w6SsRb-phdoGFfdVX0EMGS1moOnRAPffCUKvQpK-N_aTi
  authorizeUrl: https://login.dingtalk.com/oauth2/auth?
  accessTokenUrl: https://api.dingtalk.com/v1.0/oauth2/userAccessToken
  redirectUrl: http%3A%2F%2Flocalhost%2Foauth2%2Fcallback
  userInfoUrl: http://localhost:8080
sa-token:
  token-name: hjxtoken
  timeout: -1
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
server:
  port: 80
logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:mm:ss}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}){faint}  %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl